from django.urls import path
from .views import *
urlpatterns = [
    path('feed', UserFeedView.as_view(), name='user_feed'),
    path('feed_post/<int:pk>', FeedPostDetailView.as_view(),
         name='feed_post_detail'),
    path('feed_post/list', FeedPostListView.as_view(), name='feed_post_list'),
    path('feed_post/update', FeedPostUpdateView.as_view(), name='update_feed_post'),
    path('feed_post/delete/<int:pk>',
         FeedPostDeleteView.as_view(), name='delete_feed_post'),
    path('feed_post/update/tags', FeedPostTagsUpdateView.as_view(),
         name='update_feed_post_tags'),
    path('feed_post/update/likes', FeedPostLikesUpdateView.as_view(),
         name='update_feed_post_likes'),
    path('feed_post/delete/tags/<int:pk_post>/<slug:tag_name>',
         FeedPostTagsDeleteView.as_view(), name='delete_feed_post_tags'),
    path('feed_post/delete/likes/<int:pk>',
         FeedPostLikesDeleteView.as_view(), name='delete_feed_post_likes'),
    path('feed_post/update/share', FeedPostShareUpdateView.as_view(),
         name='update_feed_post_share'),
    path('feed_post/delete/share/<int:pk>',
         FeedPostShareDeleteView.as_view(), name='delete_feed_post_share'),
    path('feed_post/update/media/<int:pk>', FeedPostMediaUpdateView.as_view(),
         name='update_feed_post_media'),
    path('feed_post/delete/media/<int:pk>',
         FeedPostMediaDeleteView.as_view(), name='delete_feed_post_media'),
    path('feed_post/latest', LatestFeedPostView.as_view(), name='latest_feed_post'),
    path('feed_post/search', FeedPostSearchView.as_view(),
         name='search_feed_posts'),
    # Comments
    path('comment/<int:pk>', CommentDetailView.as_view(), name='comment_detail'),
    path('comment/list', CommentListView.as_view(), name='comment_list'),
    path('comment/create', CommentCreateView.as_view(), name='create_comment'),
    path('comment/update', CommentUpdateView.as_view(), name='update_comment'),
    path('comment/delete/<int:pk>',
         CommentDeleteView.as_view(), name='delete_comment'),
    path('comment/update/likes', CommentLikesUpdateView.as_view(),
         name='update_comment_likes'),
    path('comment/delete/likes/<int:pk>',
         CommentLikesDeleteView.as_view(), name='delete_comment_likes'),
     # UserPost
    path('user_post/create', UserPostCreateView.as_view(), name='create_user_post'),
    # Community Posts
    path('community_post/create', CommunityPostCreateView.as_view(),
         name='create_community_post'),
    path('community_post/latest', LatestCommunityPostView.as_view(),
         name='latest_community_post'),
    path('community_post/search', CommunityPostSearchView.as_view(),
         name='search_community_posts'),
]
