# Generated by Django 4.2 on 2023-05-04 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('community', '0004_community_community_photo_community_member_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0016_communitypost_title_userpost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(default='', max_length=10000)),
                ('media', models.FileField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(default='', max_length=1000)),
                ('shared_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('privacy_level', models.SmallIntegerField(default=0)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.community')),
                ('likers', models.ManyToManyField(blank=True, related_name='%(class)s_likers', to=settings.AUTH_USER_MODEL)),
                ('poster', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_poster', to=settings.AUTH_USER_MODEL)),
                ('shared_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tags', models.ManyToManyField(blank=True, to='feed.tags')),
            ],
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='likers',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='shared_type',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='tags',
        ),
        migrations.DeleteModel(
            name='CommunityPost',
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
        migrations.AddIndex(
            model_name='feedpost',
            index=models.Index(fields=['shared_type', 'shared_id'], name='feed_feedpo_shared__11e250_idx'),
        ),
    ]
