# Generated by Django 4.2 on 2023-05-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_feedpost_remove_userpost_likers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
