# Generated by Django 4.1.7 on 2023-05-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_rename_exercisesessions_exercisesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseregime',
            name='title',
        ),
    ]
