# Generated by Django 4.2 on 2023-05-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0018_remove_exerciseregime_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseDetails',
            new_name='ExerciseRegimeInfo',
        ),
    ]
