# Generated by Django 4.2 on 2023-05-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0020_remove_exercise_exercises_e_shared__26d786_idx_and_more'),
        ('feed', '0017_feedpost_remove_userpost_likers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='feedpost_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.feedpost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseregime',
            name='feedpost_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feed.feedpost'),
            preserve_default=False,
        ),
    ]
