# Generated by Django 4.2 on 2023-05-04 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_feedpost_remove_userpost_likers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0021_exercise_feedpost_ptr_exerciseregime_feedpost_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='feedpost_ptr',
        ),
        migrations.RemoveField(
            model_name='exerciseregime',
            name='feedpost_ptr',
        ),
        migrations.AddField(
            model_name='exercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_likers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='posted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='poster',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_poster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(blank=True, to='feed.tags'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='text',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='exerciseregime',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseregime',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_likers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciseregime',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciseregime',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='exerciseregime',
            name='posted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exerciseregime',
            name='poster',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(class)s_poster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exerciseregime',
            name='tags',
            field=models.ManyToManyField(blank=True, to='feed.tags'),
        ),
        migrations.AddField(
            model_name='exerciseregime',
            name='text',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
