# Generated by Django 4.2 on 2023-05-05 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0022_remove_exercise_feedpost_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseregimeinfo',
            name='set_count',
        ),
    ]
